05-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Models/ErrorViewModel.cs
using System;

namespace _05_Fiap.Web.AspNet.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

05-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Models/Tipo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _05_Fiap.Web.AspNet.Models
{
    public enum Tipo
    {
        Particular, Estatal
    }
}

05-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Models/Zoo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace _05_Fiap.Web.AspNet.Models
{
    [Table("TblZoo")]
    public class Zoo
    {
        [Column("Id")]
        public int ZooId { get; set; }

        public int Jaulas { get; set; }

        [Required, DataType(DataType.Date), Display(Name = "Data de Lançamento")]
        public DateTime DataAbertura { get; set; }

        [Required, MaxLength(50)]
        public string Nome { get; set; }        

        [Display(Name ="Tipo")]
        public Tipo EntidadeAdministradora { get; set; }



    }
}

05-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Controllers/CadastroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _05_Fiap.Web.AspNet.Models;
using _05_Fiap.Web.AspNet.Persistence;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace _05_Fiap.Web.AspNet.Controllers
{
    public class CadastroController : Controller
    {
        //o cara que acessa o banco
        private AllZooContext _context;

        public CadastroController(AllZooContext context)
        {
            _context = context;
        }
        //private static IList<Zoo> _lista = new List<Zoo>();

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Listar()
        {
            return View(_context.Zoos.ToList());
        }

        public IActionResult Buscar(int id)
        {
            var busca = _context.Zoos.Find(id);
            return View(busca);
        }


        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(Zoo zoo)
        {
            _context.Zoos.Add(zoo);
            _context.SaveChanges();
            TempData["msg"] = "Cadastrado!";
            return View(zoo);
        }

        [HttpDelete]
        public IActionResult Deletar(int id)
        {
            Zoo zoo = _context.Zoos.Find(id);
            _context.Zoos.Remove(zoo);
            _context.SaveChanges();
            TempData["msg"] = "Deletado!";
            return View();
        }
        [HttpPut]
        public IActionResult Editar(int id)
        {
            Zoo zoo = _context.Zoos.Find(id);            
            _context.Attach(zoo).State = EntityState.Modified;
            _context.SaveChanges();
            return View();
        }
    }
}

05-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using _05_Fiap.Web.AspNet.Models;

namespace _05_Fiap.Web.AspNet.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

05-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Views/Cadastro/Editar.cshtml
@model Zoo

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<div class="form-row">
    <form asp-action="Cadastrar" asp-controller="Cadastro">
        <div class="form-group">
            <label asp-for="Jaulas"></label>
            <input asp-for="Jaulas" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="DataAbertura"></label>
            <input asp-for="DataAbertura" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Nome"></label>
            <input asp-for="Nome" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="EntidadeAdministradora"></label>
            <select asp-for="EntidadeAdministradora" class="form-control" asp-items="@Html.GetEnumSelectList<Tipo>()">
                <option>Selecione</option>
            </select>

        </div>
        <botao></botao>

    </form>
</div>

05-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Views/Cadastro/Listar.cshtml
@model IList<Zoo>

@{
    ViewData["Title"] = "Listar";
}

<h1>Listar</h1>

<mensagem texto="@TempData["msg"]"></mensagem>

<table>
    <tr>
        <th>Nome</th>
        <th>Jaulas</th>
        <th>Tipo</th>
        <th>Data Abertura</th>
    </tr>
    @foreach (var item in @Model)
    {
        <tr>
            <th>@item.Nome</th>
            <th>@item.Jaulas</th>
            <th>@item.EntidadeAdministradora</th>
            <th>@item.DataAbertura.ToShortDateString()</th>
        </tr>
    }
</table>

05-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Views/Cadastro/cadastrar.cshtml
@model Zoo

@{
    ViewData["Title"] = "cadastrar";
}

@{
    Layout = "_Layout";
}


<h1>Cadastrar</h1>

<div class="form-row">
    <form asp-action="Cadastrar" asp-controller="Cadastro">
        <div class="form-group">
            <label asp-for="Jaulas"></label>
            <input asp-for="Jaulas" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="DataAbertura"></label>
            <input asp-for="DataAbertura" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Nome"></label>
            <input asp-for="Nome" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="EntidadeAdministradora"></label>
            <select asp-for="EntidadeAdministradora" class="form-control" asp-items="@Html.GetEnumSelectList<Tipo>()">
                <option>Selecione</option>
            </select>

        </div>
        <botao></botao>

    </form>
</div>

05-Fiap.Web.AspNet/05-Fiap.Web.AspNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _05_Fiap.Web.AspNet</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_05_Fiap.Web.AspNet</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - _05_Fiap.Web.AspNet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>