04-Fiap.Web.AspNet/04-Fiap.Web.AspNet/Models/ErrorViewModel.cs
using System;

namespace _04_Fiap.Web.AspNet.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

04-Fiap.Web.AspNet/04-Fiap.Web.AspNet/Models/Time.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace _04_Fiap.Web.AspNet.Models
{
    public class Time   
    {
        public string Nome { get; set; }
        public bool Classificado { get; set; }
        public int Vitorias { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Data de Fundação")]
        public DateTime DataFundacao { get; set; }

        [Display(Name = "Folha de Pagamento")]
        public decimal FolhaPagamento { get; set; }
    }
}

04-Fiap.Web.AspNet/04-Fiap.Web.AspNet/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using _04_Fiap.Web.AspNet.Models;

namespace _04_Fiap.Web.AspNet.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

04-Fiap.Web.AspNet/04-Fiap.Web.AspNet/Controllers/TimeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _04_Fiap.Web.AspNet.Models;
using Microsoft.AspNetCore.Mvc;

namespace _04_Fiap.Web.AspNet.Controllers
{
    public class TimeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        private static IList<Time> _lista = new List<Time>();

        public IActionResult Listar()
        {
            return View(_lista);
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Cadastrar(Time time)
        {
            _lista.Add(time);
            TempData["msg"] = "Cadastrado com sucesso!";
            return RedirectToAction("Listar");
        }
    }
}

04-Fiap.Web.AspNet/04-Fiap.Web.AspNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _04_Fiap.Web.AspNet</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_04_Fiap.Web.AspNet</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - _04_Fiap.Web.AspNet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

04-Fiap.Web.AspNet/04-Fiap.Web.AspNet/Views/Time/Listar.cshtml
@model IList<Time>

@{
    ViewData["Title"] = "Listar";
}

<h2>Listar</h2>

@if (TempData["msg"] != null)
<div class="alert alert-sucesss">
    @TempData["msg"]
</div>

<a asp-action="Cadastrar" asp-controller="Time" class="btn btn-outline-dark">Cadastrar</a>

<table class="table">
    <tr>
        <th>Nome</th>
        <th>Data Fundação</th>
        <th>Folha</th>
        <th>Vitórias</th>
        <th>Classificado</th>
    </tr>
    @foreach (var item in Model)
    {
     <tr>
        <td>@item.Nome</td>
        <td>@item.DataFundacao.ToShortDateString()</td>
        <td>@item.FolhaPagamento</td>
        <td>@item.Vitorias</td>
        <td>@(item.Classificado?"Sim":"Não")</td>
    </tr>
    }
    </table>

04-Fiap.Web.AspNet/04-Fiap.Web.AspNet/Views/Time/cadastrar.cshtml
@model Time

@{
    ViewData["Title"] = "cadastrar";
}

<h1 class="">Cadastrar</h1>

<div class="form-row">
    <form asp-action="Cadastrar" asp-controller="Time">
        <div class="form-group">
            <label asp-for="Nome"></label>
            <input asp-for="Nome" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="DataFundacao"></label>
            <input asp-for="DataFundacao" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Nome"></label>
            <input asp-for="Nome" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="EntidadeAdministradora"></label>
            <input asp-for="EntidadeAdministradora" class="form-control" />
        </div>

        <input type="submit" class="btn btn-outline-dark" value="OK" />
        <a asp-controller="Zoo" asp-action="Listar" class="btn btn-outline-dark">Listar</a>

    </form>
</div>